//#region imports
import * as os from 'os'; // @backend

import {
  provideClientHydration,
  withEventReplay,
} from '@angular/platform-browser';
import {
  provideRouter,
  Router,
  RouterLinkActive,
  RouterModule,
  RouterOutlet,
  ActivatedRoute,
  Routes,
  Route,
  withHashLocation,
  withComponentInputBinding,
} from '@angular/router';
import { provideServiceWorker } from '@angular/service-worker';
import { provideServerRendering, withRoutes } from '@angular/ssr';
import { RenderMode, ServerRoute } from '@angular/ssr';

import { BehaviorSubject, Observable, map, switchMap } from 'rxjs';
import {
  Taon,
  TaonBaseContext,
  TAON_CONTEXT,
  EndpointContext,
  TaonBaseAngularService,
  TaonEntity,
  StringColumn,
  TaonBaseAbstractEntity,
  TaonBaseCrudController,
  TaonController,
  GET,
  TaonMigration,
  TaonBaseMigration,
  TaonContext,
} from 'taon/src';

import { TaonStor } from 'taon-storage/src';

import { Utils, UtilsOs } from 'tnp-core/src';

import { HOST_CONFIG } from './app.hosts';
import { ENV_ANGULAR_NODE_APP_BUILD_PWA_DISABLE_SERVICE_WORKER } from './lib/env/env.angular-node-app';
// @placeholder-for-imports
//#endregion

//#region constants
console.log('🚀 [ TAON IS STARTING (server=1) ]');
//#endregion

//#region  backend-backend-realtime-server-1 entity
@TaonEntity({ className: 'UserServer1' })
class UserServer1 extends TaonBaseAbstractEntity {
  //#region @websql
  @StringColumn()
  //#endregion
  name?: string;

  getHello(): string {
    return `hello ${this.name}`;
  }
}
//#endregion

//#region  backend-backend-realtime-server-1 controller
@TaonController({ className: 'UserServer1Controller' })
class UserServer1Controller extends TaonBaseCrudController<UserServer1> {
  // eslint-disable-next-line @typescript-eslint/explicit-function-return-type
  entityClassResolveFn = () => UserServer1;

  @GET()
  helloWorld(): Taon.Response<string> {
    //#region @websqlFunc
    return async (req, res) => 'hello world';
    //#endregion
  }

  @GET()
  getOsPlatform(): Taon.Response<string> {
    //#region @websqlFunc
    return async (req, res) => {
      //#region @backend
      return os.platform(); // for normal nodejs backend return real value
      //#endregion

      return 'no-platform-inside-browser-and-websql-mode';
    };
    //#endregion
  }
}
//#endregion

//#region  backend-backend-realtime-server-1 migration

//#region @websql
@TaonMigration({
  className: 'UserServer1Migration',
})
class UserServer1Migration extends TaonBaseMigration {
  userController = this.injectRepo(UserServer1);

  async up(): Promise<any> {
    const superAdmin = new UserServer1();
    superAdmin.name = 'super-admin';
    await this.userController.save(superAdmin);
  }
}
//#endregion

//#endregion

//#region  backend-backend-realtime-server-1 context
var BackendBackendRealtimeServer1Context = Taon.createContext(() => ({
  ...HOST_CONFIG['BackendBackendRealtimeServer1Context'],
  contexts: { TaonBaseContext },

  //#region @websql
  /**
   * In production use specyfic for this context name
   * generated migration object from  ./migrations/index.ts.
   */
  migrations: {
    UserServer1Migration,
  },
  //#endregion

  controllers: {
    UserServer1Controller,
  },
  entities: {
    UserServer1,
  },
  database: true,
  disabledRealtime: true,
}));
//#endregion

//#region  backend-backend-realtime-server-1 start function
export const BackendBackendRealtimeServer1StartFunction = async (
  startParams?: Taon.StartParams,
): Promise<void> => {
  await BackendBackendRealtimeServer1Context.initialize();

  //#region initialize auto generated active contexts
  const autoGeneratedActiveContextsForApp: TaonContext[] = [
    // @placeholder-for-contexts-init
  ];

  const priorityContexts = [
    // put here manual priority for contexts if needed
  ];

  const activeContextsForApp: TaonContext[] = [
    ...priorityContexts,
    ...autoGeneratedActiveContextsForApp.filter(
      c => !priorityContexts.includes(c),
    ),
  ];

  for (const activeContext of activeContextsForApp) {
    await activeContext.initialize();
  }
  //#endregion

  //#region @backend
  if (
    startParams?.onlyMigrationRun ||
    startParams?.onlyMigrationRevertToTimestamp
  ) {
    process.exit(0);
  }
  //#endregion

  //#region @backend
  console.log(`Hello in NodeJs backend! os=${os.platform()}`);
  //#endregion
};
//#endregion

//#region default export
export default BackendBackendRealtimeServer1StartFunction;
//#endregion
