//#region imports
import * as os from 'os'; // @backend

import {
  Taon,
  TaonBaseContext,
  EndpointContext,
  TaonEntity,
  StringColumn,
  TaonBaseAbstractEntity,
  TaonController,
  GET,
  TaonContext,
  TaonBaseController,
} from 'taon/src';

import { HOST_CONFIG } from './app.hosts';
import { BackendBackendRealtimeServer1ContextRemote, UserServer1 } from './app.server1';
// @placeholder-for-imports
//#endregion

//#region constants
console.log('🚀 [ TAON IS STARTING (server=2) ]');
//#endregion

//#region  backend-backend-realtime-server-2 entity
@TaonEntity({ className: 'UserServer2' })
export class UserServer2 extends TaonBaseAbstractEntity {
  //#region @websql
  @StringColumn()
  //#endregion
  name?: string;

  getHello(): string {
    return `hello ${this.name}`;
  }
}
//#endregion

//#region  backend-backend-realtime-server-2 controller
@TaonController({ className: 'UserServer2Controller' })
export class UserServer2Controller extends TaonBaseController<UserServer2> {
  // eslint-disable-next-line @typescript-eslint/explicit-function-return-type
  entityClassResolveFn = () => UserServer2;

  @GET()
  notifyS1(): Taon.Response<string> {
    //#region @websqlFunc
    return async (req, res) => {
      const instances1 = BackendBackendRealtimeServer1ContextRemote;
      instances1.realtime.server.triggerCustomEvent('dupa', {
        notifyS1: 'notifyS1',
        ...(req.query || {}),
      });

      return 'S1 notified';
    };
    //#endregion
  }

  @GET()
  notifyS1Table(): Taon.Response<string> {
    //#region @websqlFunc
    return async (req, res) => {
      const instances1 = BackendBackendRealtimeServer1ContextRemote;
      instances1.realtime.server.triggerEntityPropertyChanges(
        UserServer1,
        'name',
        '22',
      );

      return 'S1 notified';
    };
    //#endregion
  }

  @GET()
  notifySelf(): Taon.Response<string> {
    //#region @websqlFunc
    return async (req, res) => {
      const instances1 = BackendBackendRealtimeServer2Context;
      instances1.realtime.client.triggerCustomEvent('dupa', {
        notifySelf: 'notifySelf',
      });

      return 'self notified';
    };
    //#endregion
  }
}
//#endregion

//#region  backend-backend-realtime-server-2 context
export var BackendBackendRealtimeServer2Context = Taon.createContext(() => ({
  ...HOST_CONFIG['BackendBackendRealtimeServer2Context'],
  contexts: { TaonBaseContext },

  controllers: {
    UserServer2Controller,
  },
  entities: {
    UserServer2,
  },
  database: true,
  logs: {
    realtime: true,
    // framework: true,
  },
  // disabledRealtime: true,
}));
//#endregion

export const BackendBackendRealtimeServer2ContextRemote =
  BackendBackendRealtimeServer2Context.cloneAsRemote();

//#region  backend-backend-realtime-server-2 start function
export const BackendBackendRealtimeServer2StartFunction = async (
  startParams?: Taon.StartParams,
): Promise<void> => {
  await BackendBackendRealtimeServer2Context.initialize();
  await BackendBackendRealtimeServer1ContextRemote.initialize();

  BackendBackendRealtimeServer2Context.realtime.client
    .listenChangesCustomEvent('dupa')
    .subscribe(data => {
      console.log('s2 client receiving data', { data });
    });

  BackendBackendRealtimeServer2Context.realtime.server
    .listenChangesCustomEvent('dupa')
    .subscribe(data => {
      console.log('s2 server receiving data', { data });
    });

  //#region initialize auto generated active contexts
  const autoGeneratedActiveContextsForApp: TaonContext[] = [
    // @placeholder-for-contexts-init
  ];

  const priorityContexts = [
    // put here manual priority for contexts if needed
  ];

  const activeContextsForApp: TaonContext[] = [
    ...priorityContexts,
    ...autoGeneratedActiveContextsForApp.filter(
      c => !priorityContexts.includes(c),
    ),
  ];

  for (const activeContext of activeContextsForApp) {
    await activeContext.initialize();
  }
  //#endregion

  //#region @backend
  if (
    startParams?.onlyMigrationRun ||
    startParams?.onlyMigrationRevertToTimestamp
  ) {
    process.exit(0);
  }
  //#endregion

  //#region @backend
  console.log(`Hello in NodeJs backend! os=${os.platform()}`);
  //#endregion
};
//#endregion

//#region default export
export default BackendBackendRealtimeServer2StartFunction;
//#endregion
