//#region imports
import * as os from 'os'; // @backend

import {
  Taon,
  TaonBaseContext,
  EndpointContext,
  TaonEntity,
  StringColumn,
  TaonBaseAbstractEntity,
  TaonController,
  GET,
  TaonContext,
  TaonBaseController,
} from 'taon/src';

import { HOST_CONFIG } from './app.hosts';
import { BackendBackendRealtimeServer2ContextRemote } from './app.server2';
// @placeholder-for-imports
//#endregion

//#region constants
console.log('🚀 [ TAON IS STARTING (server=1) ]');

//#endregion

//#region  backend-backend-realtime-server-1 entity
@TaonEntity({ className: 'UserServer1' })
export class UserServer1 extends TaonBaseAbstractEntity {
  //#region @websql
  @StringColumn()
  //#endregion
  name?: string;

  getHello(): string {
    return `hello ${this.name}`;
  }
}
//#endregion

//#region  backend-backend-realtime-server-1 controller
@TaonController({ className: 'UserServer1Controller' })
export class UserServer1Controller extends TaonBaseController<UserServer1> {
  // eslint-disable-next-line @typescript-eslint/explicit-function-return-type
  entityClassResolveFn = () => UserServer1;

  @GET()
  notifyS2(): Taon.Response<string> {
    //#region @websqlFunc
    return async (req, res) => {
      const instances2 = BackendBackendRealtimeServer2ContextRemote;
      instances2.realtime.server.triggerCustomEvent('dupa', {
        notifyS2: 'notifyS2',
        ...(req.query || {}),
      });

      return 'S2 notified';
    };
    //#endregion
  }

  @GET()
  notifySelf(): Taon.Response<string> {
    //#region @websqlFunc
    return async (req, res) => {
      const instances1 = BackendBackendRealtimeServer1Context;
      instances1.realtime.server.triggerCustomEvent('dupa', {
        notifySelf: 'notifySelf',
      });

      return 'self notified';
    };
    //#endregion
  }
}
//#endregion

//#region  backend-backend-realtime-server-1 context
export var BackendBackendRealtimeServer1Context = Taon.createContext(() => ({
  ...HOST_CONFIG['BackendBackendRealtimeServer1Context'],
  contexts: { TaonBaseContext },

  controllers: {
    UserServer1Controller,
  },
  entities: {
    UserServer1,
  },
  database: true,
  logs: {
    realtime: true,
    // framework: true,
  },
  // disabledRealtime: true,
}));
//#endregion

export const BackendBackendRealtimeServer1ContextRemote =
  BackendBackendRealtimeServer1Context.cloneAsRemote();

//#region  backend-backend-realtime-server-1 start function
export const BackendBackendRealtimeServer1StartFunction = async (
  startParams?: Taon.StartParams,
): Promise<void> => {
  await BackendBackendRealtimeServer1Context.initialize();
  await BackendBackendRealtimeServer2ContextRemote.initialize();

  BackendBackendRealtimeServer1Context.realtime.client
    .listenChangesCustomEvent('dupa')
    .subscribe(data => {
      console.log('s1 client receiving data', { data });
    });

  BackendBackendRealtimeServer1Context.realtime.server
    .listenChangesCustomEvent('dupa')
    .subscribe(data => {
      console.log('s1 server receiving data', { data });
    });

  BackendBackendRealtimeServer1Context.realtime.client
    .listenChangesEntity(UserServer1, {
      idOrUniqValue: 'name',
    })
    .subscribe(data => {
      console.log('s1 UserServer1 receiving data', { data });
    });

  //#region initialize auto generated active contexts
  const autoGeneratedActiveContextsForApp: TaonContext[] = [
    // @placeholder-for-contexts-init
  ];

  const priorityContexts = [
    // put here manual priority for contexts if needed
  ];

  const activeContextsForApp: TaonContext[] = [
    ...priorityContexts,
    ...autoGeneratedActiveContextsForApp.filter(
      c => !priorityContexts.includes(c),
    ),
  ];

  for (const activeContext of activeContextsForApp) {
    await activeContext.initialize();
  }
  //#endregion

  //#region @backend
  if (
    startParams?.onlyMigrationRun ||
    startParams?.onlyMigrationRevertToTimestamp
  ) {
    process.exit(0);
  }
  //#endregion

  //#region @backend
  console.log(`Hello in NodeJs backend! os=${os.platform()}`);
  //#endregion
};
//#endregion

//#region default export
export default BackendBackendRealtimeServer1StartFunction;
//#endregion
